# Generated by Django 5.1.4 on 2025-01-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.TextField(max_length=100)),
                ('bairro', models.TextField(max_length=100)),
                ('cidade', models.TextField(max_length=100)),
                ('estado', models.TextField(max_length=100)),
                ('pais', models.TextField(max_length=100)),
            ],
        ),
    ]
