# Generated by Django 5.1.4 on 2025-01-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='nascimento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='sexo',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.IntegerField(null=True),
        ),
    ]
