# Generated by Django 5.1.4 on 2025-01-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_pessoa_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='id',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='id_pessoa',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
