# Generated by Django 5.1.4 on 2025-01-21 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_remove_pessoa_id_pessoa_id_pessoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='id_pessoa',
            new_name='id',
        ),
    ]
