# Generated by Django 5.1.4 on 2025-01-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_rename_id_pessoa_pessoa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='idade',
            field=models.TextField(max_length=20),
        ),
    ]
