# Generated by Django 5.1.4 on 2025-01-22 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_alter_pessoa_idade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='nascimento',
        ),
    ]
