# Generated by Django 5.1.4 on 2025-01-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_remove_pessoa_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.TextField(null=True),
        ),
    ]
